version: '3.8'
services:
  web:
    build: .
    ports:
    - "5001:5000"
    volumes:
    - .:/opt
    links:
    - myredis
  myredis:
    image: redis:6.2.1
    volumes:
      - redis-data:/var/lib/redis

volumes:
  redis-data:

